site_name: pytest-mimic
site_description: Easily record function calls while testing
site_author: Teo Cherici

theme: readthedocs

repo_url: https://github.com/clockworks-data/pytest-mimic

nav:
  - Home: index.md
  - Usage Guide: usage.md
  - Advanced Features: advanced.md
  - API Reference: api.md
  - Examples: examples.md
